### ISSUE TITLE
Architecture not set on file correctly

### ISSUE THREAD

**Issue by spinus** [tcurdt/jdeb#180]
In debian control file I set:

```
Package: [[debian.package.name]]-[[debian.package.version]]
Version: [[debian.package.version]]
Section: admin
Priority: optional
Depends: [[debian.package.dependencies]]
Architecture: amd64
Maintainer: xxx
Description: [[debian.package.description]]
Distribution: [[debian.package.distribution]]
```

But the file has name like

```
project-name_version_all.deb
```

I'm not sure it's an issue or I cannot configure it properly.

**Comment by TuireHolappa** [comment]
I was not able to successfully use the workaround for defining <deb> for SNAPSHOT builds.

**Comment by tcurdt** [comment]
@TuireHolappa you have to be a little more specific in case you want help.

**Comment by TuireHolappa** [comment]
No help needed I just wanted to inform you the situation.

The workaround for setting the <deb> like in the comment from Spinus did
not work for with the  -SNAPSHOT versions:

Caused by: org.vafer.jdeb.PackagingException: Failed to create debian
package mysoftware-0.0.4-SNAPSHOT_i386.deb
        at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:333)
        at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:567)
        ... 22 more
Caused by: org.vafer.jdeb.PackagingException: Could not create deb package
        at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:554)
        at org.vafer.jdeb.DebMaker.createDeb(DebMaker.java:448)
        at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:329)
        ... 23 more
Caused by: java.lang.NullPointerException
        at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:499)


So I ended up using  a dirty solution of renaming the .deb file afterwards


So the functionality to take the architecture to the file name from the
configuration (control or even more preferably from Maven configuration to
both) would be appreciated.



2016-08-26 13:04 GMT+03:00 Torsten Curdt <notifications@github.com>:

**Comment by tcurdt** [comment]
I would check why this is happening - but this stacktrace either does not match master or is cut off

```
Caused by: java.lang.NullPointerException
        at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:499)

```

**Comment by TuireHolappa** [comment]
I suspect it could be related to the -SNAPSHOT in the version instead of
the normally produced  ~SNAPSHOT.

The jdeb version is 1.5 and otherwise it works nicely :). I really like it
and hope it will be accepted to be taken it in to use in our projects.

Yes I did cut the trace. Sorry. Here the whole thing:

[ERROR] Failed to execute goal org.vafer:jdeb:1.5:jdeb (default) on project
train-topology-data: Failed to create debian package mypackage-0
.0.4-SNAPSHOT_i386.deb: Could not create deb package: NullPointerException
-> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute
goal org.vafer:jdeb:1.5:jdeb (default) on project mypackage: Faile
d to create debian package mypackage-0.0.4-SNAPSHOT_i386.deb
        at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at
org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at
org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at
org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at
org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create
debian package mypackage-0.0.4-SNAPSHOT_i386.deb
        at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:581)
        at
org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.vafer.jdeb.PackagingException: Failed to create debian
package mypackage-0.0.4-SNAPSHOT_i386.deb
        at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:333)
        at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:567)
        ... 22 more
Caused by: org.vafer.jdeb.PackagingException: Could not create deb package
        at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:554)
        at org.vafer.jdeb.DebMaker.createDeb(DebMaker.java:448)
        at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:329)
        ... 23 more
Caused by: java.lang.NullPointerException
        at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:499)
        ... 25 more

2016-08-26 14:32 GMT+03:00 Torsten Curdt <notifications@github.com>:

**Comment by tcurdt** [comment]
So [here](https://github.com/tcurdt/jdeb/blob/jdeb-1.5/src/main/java/org/vafer/jdeb/DebMaker.java#L499) is where it fails

```
deb.getParentFile().mkdirs();
```

https://docs.oracle.com/javase/7/docs/api/java/io/File.html#getParentFile()

> Returns the abstract pathname of this abstract pathname's parent, or null if this pathname does not name a parent directory.
> The parent of an abstract pathname consists of the pathname's prefix, if any, and each name in the pathname's name sequence except for the last. If the name sequence is empty then the pathname does not name a parent directory.
> 

So either `deb` is `null` or `getParentFile` returns `null`.
