### ISSUE TITLE
Jdeb does NOT work with Centos 6.6 (final)

### ISSUE THREAD

**Issue by jaroslawZawila** [tcurdt/jdeb#192]
Hello, 

I have project which use jdeb to build deb file. I used to develop on Centos 6.5 and everything works fine. I have migrated to Centos 6.6 and Jdeb plugin failing to build the deb package. The configuration for both OS is the same as I use puppet to set up all dependencies. This is the error I could see.

[INFO] --- webstart-maven-plugin:1.0-beta-4-AI:jnlp-inline (generate-jnlp-template-for-signing) @ investigator-webstart ---
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.vafer.jdeb.PackagingException: Could not create deb package
	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:527)
	at org.vafer.jdeb.DebMaker.createDeb(DebMaker.java:418)
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:294)
	... 22 more
Caused by: java.io.IOException: This archives contains unclosed entries.
	at org.vafer.jdeb.shaded.compress.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:219)
	at org.vafer.jdeb.shaded.compress.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:235)
	at org.vafer.jdeb.DataBuilder.buildData(DataBuilder.java:279)
	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:440)
	... 24 more

**Comment by tcurdt** [comment]
`jdeb` uses only shaded dependencies - so something must be different.
What about the java and maven versions?

**Comment by jaroslawZawila** [comment]
Both boxes runs on 
 - java 1.6.0_45
 - maven Maven 3.1.1

**Comment by tcurdt** [comment]
If nothing in the jvm space has changed there should be no error. Hard to debug.

Since you have puppet setup. Do you think you could create a virtualbox vm or docker container to replicate this?

Either that or I fear you would have to debug this yourself.

**Comment by tcurdt** [comment]
Any progress?

**Comment by tcurdt** [comment]
Closing because of lack of feedback.
