### ISSUE TITLE
Key and passphrase are not found

### ISSUE THREAD

**Issue by mondain** [tcurdt/jdeb#201]
I've tried both version 1.3 and 1.4. The only way this works is to put the items in the pom; I need this to work using my settings.xml since its for a public project. Heres the error I get with and without using the "jdeb." prefix:

```
[WARNING] Signing requested, but no key supplied
[WARNING] Signing requested, but no passphrase supplied
[ERROR] Failed to create debian package /home/mondain/workspace/github-red5/installer/debian/target/red5-server_1.0.5_all.deb
org.vafer.jdeb.PackagingException: Failed to create debian package /home/mondain/workspace/github-red5/installer/debian/target/red5-server_1.0.5_all.deb
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:296)
	at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:552)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NullPointerException
	at org.vafer.jdeb.signing.PGPSigner.getSecretKey(PGPSigner.java:146)
	at org.vafer.jdeb.signing.PGPSigner.<init>(PGPSigner.java:54)
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:280)
	... 22 more

```

**Comment by tcurdt** [comment]
Since it's a public project - got a link to the sources?

**Comment by tcurdt** [comment]
I guess it needs debugging in here https://github.com/tcurdt/jdeb/blob/6430547c14d4cbee5ebd50f597206e9e98e9e0c7/src/main/java/org/vafer/jdeb/maven/DebMojo.java#L586

**Comment by mondain** [comment]
Heres the link to the debian part: https://github.com/Red5/installer/tree/master/debian

**Comment by alegrm** [comment]
I could use the configuration from settings.xml if I put the profile in the maven command  (i.e. mvn  package -Pjdeb-signing)

**Comment by tcurdt** [comment]
@mondain did you try passing the profile like @alegrm suggested?

**Comment by tcurdt** [comment]
no feedback provided. closing for now.

**Comment by mondain** [comment]
Sorry, no, I have not; I've not looked into building the deb for Red5 is quite some time now. I'll try the workaround on our next release.
