### ISSUE TITLE
Maven can't create debian package: throws exceptions

### ISSUE THREAD

**Issue by ChaparinAlex** [tcurdt/jdeb#252]
Hi!
Can anybody help me? I made a JavaFX project in Maven and need to obtain deb-package. But Maven throws exceptions. I add my POM-file and exception info (see below).

POM:
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>ShipsBattleGUI</groupId>
  <artifactId>ShipsBattleGUI</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <organization>
    <name>My Organization</name>
  </organization>
  
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.3</version>
         <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
       </plugin> 
       
       <plugin>
        <groupId>com.zenjava</groupId>
        <artifactId>javafx-maven-plugin</artifactId>
        <version>8.7.0</version>   
        <configuration>
          <mainClass>com.chaparin.Main</mainClass>
          <nativeInstallers />
        </configuration>    
       </plugin>
       
        <plugin>
                <artifactId>jdeb</artifactId>
                <groupId>org.vafer</groupId>
                <version>1.5</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>jdeb</goal>
                        </goals>
                        <configuration>
                         <controlDir>${basedir}/src/deb/control</controlDir>
                         
                         <verbose>true</verbose>
                            <snapshotExpand>true</snapshotExpand>
                            
                            <snapshotEnv>USER</snapshotEnv>
                            <verbose>true</verbose>
                           
                            <dataSet>

                                <data>
                                  <src>${project.build.directory}/${project.build.finalName}.jar</src>
                                  <type>file</type>
                                  <mapper>
                                    <type>perm</type>
                                    <prefix>/usr/share/jdeb/lib</prefix>
                                    <user>loader</user>
                                    <group>loader</group>
                                  </mapper>
                                </data>

                                <data>
                                  <type>link</type>
                                  <symlink>true</symlink>
                                  <linkName>/usr/share/java/jdeb.jar</linkName>
                                  <linkTarget>/usr/share/jdeb/lib/${project.build.finalName}.jar</linkTarget>
                                </data>

                                <data>
                                  <src>${basedir}/src/deb/init.d</src>
                                  <type>directory</type>
                                  <mapper>
                                    <type>perm</type>
                                    <prefix>/etc/init.d</prefix>
                                    <user>loader</user>
                                    <group>loader</group>
                                  </mapper>
                                </data>

                                <data>
                                  <type>template</type>
                                  <paths>
                                    <path>etc/${project.artifactId}</path>
                                    <path>var/lib/${project.artifactId}</path>
                                    <path>var/log/${project.artifactId}</path>
                                    <path>var/run/${project.artifactId}</path>
                                  </paths>
                                  <mapper>
                                    <type>perm</type>
                                    <user>loader</user>
                                    <group>loader</group>
                                  </mapper>
                                </data>

                            </dataSet>
                        </configuration>
                    </execution>
                </executions>
                
                
       </plugin>
      
    </plugins>
  </build>
</project>

Exceptions:
[ERROR] Failed to create debian package C:\Users\Alex\workspace\Ship'sBattleGUI\target\ShipsBattleGUI_0.0.1~20170213233003_all.deb
org.vafer.jdeb.PackagingException: Failed to create debian package C:\Users\Alex\workspace\Ship'sBattleGUI\target\ShipsBattleGUI_0.0.1~20170213233003_all.deb
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:333)
	at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:567)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.vafer.jdeb.PackagingException: Could not create deb package
	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:554)
	at org.vafer.jdeb.DebMaker.createDeb(DebMaker.java:448)
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:329)
	... 23 more
Caused by: java.io.FileNotFoundException: C:\Users\Alex\workspace\Ship'sBattleGUI\src\deb\control\control (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.vafer.jdeb.ControlBuilder.createPackageControlFile(ControlBuilder.java:174)
	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:477)
	... 25 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.578 s
[INFO] Finished at: 2017-02-13T23:30:08+02:00
[INFO] Final Memory: 14M/180M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.vafer:jdeb:1.5:jdeb (default) on project ShipsBattleGUI: Failed to create debian package C:\Users\Alex\workspace\Ship'sBattleGUI\target\ShipsBattleGUI_0.0.1~20170213233003_all.deb: Could not create deb package: C:\Users\Alex\workspace\Ship'sBattleGUI\src\deb\control\control (The system cannot find the file specified) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by bedge** [comment]
One extra 'control'?
```
C:\Users\Alex\workspace\Ship'sBattleGUI\src\deb\control\control (The system cannot find the file specified)
```

**Comment by ChaparinAlex** [comment]
I have only one directory "control"

**Comment by bedge** [comment]
I meant the generated string is repeating the 'control' string.

The error implies that it's adding the 'control' automatically.

So, try removing the 'control' from:
```
                     <controlDir>${basedir}/src/deb/control</controlDir>
```
ie:
```
                     <controlDir>${basedir}/src/deb</controlDir>
```

Disclaimer,  have not read the docs on this, but it'd the first thing I'd try.

**Comment by ChaparinAlex** [comment]
I did it ( <controlDir>${basedir}/src/deb</controlDir>), but problem isn't disappeared.

[INFO] --- jdeb:1.5:jdeb (default) @ ShipsBattleGUI ---
[INFO] Creating debian package: C:\Users\Alex\workspace\Ship'sBattleGUI\target\ShipsBattleGUI_0.0.1~20170214000603_all.deb
[INFO] Building data
[INFO] file:./usr/share/jdeb/lib/ShipsBattleGUI-0.0.1-SNAPSHOT.jar size:2259356 mode:33188 linkname: username:loader userid:0 groupname:loader groupid:0 modtime:Tue Feb 14 00:06:07 EET 2017 md5: 306aa476abfcd671d861925639d96e17
[INFO] link:./usr/share/java/jdeb.jar mode:33188 linkname:/usr/share/jdeb/lib/ShipsBattleGUI-0.0.1-SNAPSHOT.jar username:root userid:0 groupname:root groupid:0
[INFO] dir: ./etc/ShipsBattleGUI
[INFO] dir: ./var/lib/ShipsBattleGUI
[INFO] dir: ./var/log/ShipsBattleGUI
[INFO] dir: ./var/run/ShipsBattleGUI
[INFO] Total size: 2259356
[INFO] Building conffiles
[INFO] Building control
[ERROR] Failed to create debian package C:\Users\Alex\workspace\Ship'sBattleGUI\target\ShipsBattleGUI_0.0.1~20170214000603_all.deb
org.vafer.jdeb.PackagingException: Failed to create debian package C:\Users\Alex\workspace\Ship'sBattleGUI\target\ShipsBattleGUI_0.0.1~20170214000603_all.deb
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:333)
	at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:567)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.vafer.jdeb.PackagingException: Could not create deb package
	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:554)
	at org.vafer.jdeb.DebMaker.createDeb(DebMaker.java:448)
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:329)
	... 23 more
Caused by: java.io.FileNotFoundException: C:\Users\Alex\workspace\Ship'sBattleGUI\src\deb\control (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.vafer.jdeb.ControlBuilder.createPackageControlFile(ControlBuilder.java:174)
	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:477)
	... 25 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.958 s
[INFO] Finished at: 2017-02-14T00:06:07+02:00
[INFO] Final Memory: 12M/180M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.vafer:jdeb:1.5:jdeb (default) on project ShipsBattleGUI: Failed to create debian package C:\Users\Alex\workspace\Ship'sBattleGUI\target\ShipsBattleGUI_0.0.1~20170214000603_all.deb: Could not create deb package: C:\Users\Alex\workspace\Ship'sBattleGUI\src\deb\control (The system cannot find the file specified) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by bedge** [comment]
Next thing to try would be to escape, or preferably get rid of the apostrophe in the path.
That's bad for for any platform, despite what microsoft tells you :-)
The rule is 'never use spaces or anything outside of a-zA-Z0-9_ char in path names'
It's probably being interpreted as an open quite somewhere. Bug or not, better to avoid it.

**Comment by ChaparinAlex** [comment]
I cleaned apostrophe in the path. The same problem.

**Comment by bedge** [comment]
You try putting the 'control' back?
Paste the error again.

**Comment by ChaparinAlex** [comment]
[ERROR] Failed to create debian package C:\Users\Alex\workspace\ShipsBattleGUI\target\ShipsBattleGUI_0.0.1~20170214004100_all.deb
org.vafer.jdeb.PackagingException: Failed to create debian package C:\Users\Alex\workspace\ShipsBattleGUI\target\ShipsBattleGUI_0.0.1~20170214004100_all.deb
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:333)
	at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:567)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.vafer.jdeb.PackagingException: Could not create deb package
	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:554)
	at org.vafer.jdeb.DebMaker.createDeb(DebMaker.java:448)
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:329)
	... 23 more
Caused by: java.io.FileNotFoundException: C:\Users\Alex\workspace\ShipsBattleGUI\src\deb\control (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.vafer.jdeb.ControlBuilder.createPackageControlFile(ControlBuilder.java:174)
	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:477)
	... 25 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.112 s
[INFO] Finished at: 2017-02-14T00:41:06+02:00
[INFO] Final Memory: 13M/179M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.vafer:jdeb:1.5:jdeb (default) on project ShipsBattleGUI: Failed to create debian package C:\Users\Alex\workspace\ShipsBattleGUI\target\ShipsBattleGUI_0.0.1~20170214004100_all.deb: Could not create deb package: C:\Users\Alex\workspace\ShipsBattleGUI\src\deb\control (The system cannot find the file specified) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by bedge** [comment]
OK, put the 'control' back now. I'm guessing that was a red herring, it was the apostrophe.

**Comment by ChaparinAlex** [comment]
After putting "control" back:

[INFO] --- jdeb:1.5:jdeb (default) @ ShipsBattleGUI ---
[INFO] Creating debian package: C:\Users\Alex\workspace\ShipsBattleGUI\target\ShipsBattleGUI_0.0.1~20170214004829_all.deb
[INFO] Building data
[INFO] file:./usr/share/jdeb/lib/ShipsBattleGUI-0.0.1-SNAPSHOT.jar size:2257445 mode:33188 linkname: username:loader userid:0 groupname:loader groupid:0 modtime:Tue Feb 14 00:48:33 EET 2017 md5: 9efad043401cf51638e92500e5ba0b7c
[INFO] link:./usr/share/java/jdeb.jar mode:33188 linkname:/usr/share/jdeb/lib/ShipsBattleGUI-0.0.1-SNAPSHOT.jar username:root userid:0 groupname:root groupid:0
[INFO] dir: ./etc/ShipsBattleGUI
[INFO] dir: ./var/lib/ShipsBattleGUI
[INFO] dir: ./var/log/ShipsBattleGUI
[INFO] dir: ./var/run/ShipsBattleGUI
[INFO] Total size: 2257445
[INFO] Building conffiles
[INFO] Building control
[ERROR] Failed to create debian package C:\Users\Alex\workspace\ShipsBattleGUI\target\ShipsBattleGUI_0.0.1~20170214004829_all.deb
org.vafer.jdeb.PackagingException: Failed to create debian package C:\Users\Alex\workspace\ShipsBattleGUI\target\ShipsBattleGUI_0.0.1~20170214004829_all.deb
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:333)
	at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:567)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.vafer.jdeb.PackagingException: Could not create deb package
	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:554)
	at org.vafer.jdeb.DebMaker.createDeb(DebMaker.java:448)
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:329)
	... 23 more
Caused by: java.io.FileNotFoundException: C:\Users\Alex\workspace\ShipsBattleGUI\src\deb\control\control (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.vafer.jdeb.ControlBuilder.createPackageControlFile(ControlBuilder.java:174)
	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:477)
	... 25 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.904 s
[INFO] Finished at: 2017-02-14T00:48:33+02:00
[INFO] Final Memory: 14M/180M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.vafer:jdeb:1.5:jdeb (default) on project ShipsBattleGUI: Failed to create debian package C:\Users\Alex\workspace\ShipsBattleGUI\target\ShipsBattleGUI_0.0.1~20170214004829_all.deb: Could not create deb package: C:\Users\Alex\workspace\ShipsBattleGUI\src\deb\control\control (The system cannot find the file specified) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by bedge** [comment]
Does `C:\Users\Alex\workspace\ShipsBattleGUI\src\deb\control\control` exist? And is it a file?

**Comment by ChaparinAlex** [comment]
It's a directory

**Comment by bedge** [comment]
There should be a file named control under the directory of the same name
```
%> tree deb                                                                                                                                                                    deb
├── changelog
└── control
    ├── control
    ├── postinst
    └── prerm

```

**Comment by ChaparinAlex** [comment]
Sorry, this is directory: C:\Users\Alex\workspace\ShipsBattleGUI\src\deb\control
File C:\Users\Alex\workspace\ShipsBattleGUI\src\deb\control\control isn't exist. This directory is empty

**Comment by bedge** [comment]
then that's you're problem. You have to create this file.
eg: here's a sample
```
%>  cat deb/control/control                                                                                                                                                    
Package: <name>
Version: [[version]]
Section: misc
Priority: optional
Architecture: all
Maintainer: xxxxx
Description: [[description]]
Distribution: development
```

**Comment by ChaparinAlex** [comment]
Thanks a lot. I'll try to do it later and spell about result.

**Comment by ChaparinAlex** [comment]
Everything works fine! But I can't understand following: why do I have to make this file manually? Why Maven can't build it automatic?

**Comment by tcurdt** [comment]
@ChaparinAlex This is meta data `jdeb` cannot magically create. How should it know about which Section etc.
