### ISSUE TITLE
DataProducerFilesTestCase fails on windows

### ISSUE THREAD

**Issue by tcurdt** [tcurdt/jdeb#255]
```
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.141 sec <<< FAILURE! - in org.vafer.jdeb.producers.DataProducerFilesTestCase
testProducesMultiplePathsNoDestination(org.vafer.jdeb.producers.DataProducerFilesTestCase)  Time elapsed: 0.141 sec  <<< ERROR!
Argument(s) are different! Wanted:
dataConsumer.onEachFile(
    <any>,
    
);
-> at org.vafer.jdeb.producers.DataProducerFilesTestCase.testProducesMultiplePathsNoDestination(DataProducerFilesTestCase.java:85)
Actual invocation has different arguments:
dataConsumer.onEachFile(
    java.io.FileInputStream@318f0acd,
    org.apache.commons.compress.archivers.tar.TarArchiveEntry@8e1a09a7
);
-> at org.vafer.jdeb.producers.Producers.produceInputStreamWithEntry(Producers.java:90)
	at org.vafer.jdeb.producers.DataProducerFilesTestCase.testProducesMultiplePathsNoDestination(DataProducerFilesTestCase.java:85)
Running org.vafer.jdeb.producers.DataProducerPathTemplateTestCase
```

**Comment by tcurdt** [comment]
The problem is [here](https://github.com/tcurdt/jdeb/blob/master/src/test/java/org/vafer/jdeb/producers/DataProducerFilesTestCase.java#L106
):
```
f.getAbsolutePath() = C:\Users\vagrant\AppData\Local\Temp\DataProducerFilesTestCase.15746857611704088954txt
e.getName() = /Users/vagrant/AppData/Local/Temp/DataProducerFilesTestCase.15746857611704088954txt
```
