### ISSUE TITLE
jdeb newby getting exception

### ISSUE THREAD

**Issue by Christopher-Johnston** [tcurdt/jdeb#281]
I've been trying to generate a .deb file using maven, but I'm getting an exception. I'm sure it is something simple I'm not doing correctly, but I don't know how to resolve the error. I've tried the following:

mvn -X install 
mvn -X -DsignDebian=true install
mvn -X -DsignDebian= false install

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.179 s
[INFO] Finished at: 2018-10-01T16:10:51-07:00
[INFO] Final Memory: 34M/1963M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.vafer:jdeb:1.6:jdeb (default) on project myjarpkg: Failed to create debian package /home/me/myproj/target/myjarpkg_0.01_all.deb: Could not create deb package: Empty line -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.vafer:jdeb:1.6:jdeb (default) on project myjarpkg: Failed to create debian package /home/me/myproj/target/myjarpkg_0.01_all.deb
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create debian package /home/me/myproj/target/myjarpkg_0.01_all.deb
        at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:597)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: org.vafer.jdeb.PackagingException: Failed to create debian package /home/me/myproj/target/myjarpkg_0.01_all.deb
        at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:348)
        at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:583)
        ... 22 more
Caused by: org.vafer.jdeb.PackagingException: Could not create deb package
        at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:573)
        at org.vafer.jdeb.DebMaker.createDeb(DebMaker.java:463)
        at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:344)
        ... 23 more
Caused by: java.text.ParseException: Empty line
        at org.vafer.jdeb.debian.ControlFile.parse(ControlFile.java:63)
        at org.vafer.jdeb.debian.ControlFile.parse(ControlFile.java:43)
        at org.vafer.jdeb.debian.BinaryPackageControlFile.<init>(BinaryPackageControlFile.java:60)
        at org.vafer.jdeb.ControlBuilder.createPackageControlFile(ControlBuilder.java:175)
        at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:496)
        ... 25 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

-- control -- 

Package: <name>
Version: [[version]]
Section: misc
Priority: optional
Architecture: all
Depends: jdk (>=1.8)
Maintainer: me@myco.com
Description: [[description]]
Distribution: development

-- pom.xml exerpt --

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  </properties>

  <build>
     <finalName>MyJarPkg</finalName> 
        <plugins>
            <plugin>
                <artifactId>jdeb</artifactId>
                <groupId>org.vafer</groupId>
                <version>1.6</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>jdeb</goal>
                        </goals>
			<configuration>
				
                            <verbose>true</verbose>
                            <snapshotExpand>true</snapshotExpand>
                            <snapshotEnv>USER</snapshotEnv>
                            <verbose>true</verbose>
			    <controlDir>${basedir}/src/deb/control</controlDir>

                            <dataSet>

                                <data>
                                  <src>${project.build.directory}/${project.build.finalName}.jar</src>
                                  <type>file</type>
                                  <mapper>
                                    <type>perm</type>
				    <prefix>/usr/share/jdeb/lib</prefix>
                                    <user>loader</user>
                                    <group>loader</group>
				    <filemode>640</filemode>
                                  </mapper>
                                </data>
				
                                <data>
                                  <type>link</type>
                                  <symlink>true</symlink>
                                  <linkName>/usr/share/java/jdeb.jar</linkName>
                                  <linkTarget>/usr/share/jdeb/lib/${project.build.finalName}.jar</linkTarget>
                                </data>

                                <data>
                                  <src>${basedir}/src/deb/init.d</src>
                                  <type>directory</type>
                                  <mapper>
                                    <type>perm</type>
                                    <prefix>/etc/init.d</prefix>
                                    <user>loader</user>
                                    <group>loader</group>
                                  </mapper>
                                </data>

                                <data>
                                  <type>template</type>
                                  <paths>
                                    <path>etc/${project.artifactId}</path>
                                    <path>var/lib/${project.artifactId}</path>
                                    <path>var/log/${project.artifactId}</path>
                                    <path>var/run/${project.artifactId}</path>
                                  </paths>
                                  <mapper>
                                    <type>perm</type>
                                    <user>loader</user>
                                    <group>loader</group>
                                    <filemode>750</filemode>
                                  </mapper>
                                </data>

                            </dataSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

    </plugins>
    
  </build>
  
</project>

**Comment by Christopher-Johnston** [comment]
Although not present, the control file has been tried with <name>, MyJarPkg.jar, or MyJarPkg.jar with qualified path.

**Comment by tcurdt** [comment]
The exception references
```
Caused by: java.text.ParseException: Empty line
at org.vafer.jdeb.debian.ControlFile.parse(ControlFile.java:63)
```
https://github.com/tcurdt/jdeb/blob/master/src/main/java/org/vafer/jdeb/debian/ControlFile.java#L62

IIRC empty lines are not allowed in control files.
I guess the exception could be a bit more explicit.
Just remove the empty line and try again.

**Comment by tcurdt** [comment]
Given the lack of further feedback I assume the question was answered and will close this for now.
